name: Auto-merge pull requests targeting main

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - unlocked

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-automerge:
    if: >-
      github.event.pull_request.base.ref == 'main' &&
      github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@a660677d5469627102a1c1e11409dd063606628d
        with:
          merge-method: merge
